_target_: src.training.models.task.RegressionTask

net:
  _target_: src.training.models.net.LinearRegressionNet

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
