services:
  app:
    build: .
    image: ds-image
    container_name: ds-container
    ports:
      - 8888:8888
    volumes:
      - .:/project
      - /dev/null:/project/.env  # Exclude file
    env_file:
      - .env
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
