defaults:
  - _self_
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .

model_type: ???  # simple_mlp, simple_mf, bpr_mlp, bpr_mf
execute_remotely: false
prev_task_id: null
num_workers: 0
pin_memory: false
