defaults:
  - _self_
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .

model_type: "simple_mlp"  # simple_mlp, simple_mf, bpr_mlp, bpr_mf
draft_mode: false
prev_task_id: null
num_workers: 8
pin_memory: true
