defaults:
  - override hydra/job_logging: custom
  - _self_  # Primary config overrides values of configs from the Defaults List

hydra:
  output_subdir: null
  run:
    dir: .

project_name: "MyProject"
tags: ["${now:%Y-%m-%d}"]
data_processing_task_id: null
training_task_id: null
model_type: "simple_mlp"  # simple_mlp, simple_mf
num_workers: 11
pin_memory: true
