defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .

cwd: ${hydra:runtime.cwd}
execute_remotely: false
raw_data_path: ${cwd}/data/raw_data/data.csv
split_ratio: 0.7
