defaults:
  - _self_
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .

data_type: "simple"  # simple, bpr
n_user_clicks: 5
n_item_clicks: 10
use_remote_storage: false
draft_mode: false
