defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .

data_type: "explicit"
execute_locally: true
execute_with_agent: false
