defaults:
  - _self_
  - data: movielens
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .

execute_locally: true
draft_mode: false
