defaults:
  - override hydra/job_logging: custom
  - _self_  # Primary config overrides values of configs from the Defaults List

hydra:
  output_subdir: null
  run:
    dir: .

project_name: "MyProject"
tags: ["${now:%Y-%m-%d}"]
list_size: 5
split_date: "2019/04/09"
user_history_size: 5
