defaults:
  - method: simple

  - override hydra/job_logging: custom
  - _self_  # Primary config overrides values of configs from the Defaults List

hydra:
  output_subdir: null
  run:
    dir: .

project_name: "MyProject"
use_remote_storage: false
