defaults:
  - _self_
  - datamodule: simple
  - model: cla_mlp
  - callbacks: default
  - trainer: default

  - experiment: "simple_mlp"  # Choose one from 'experiment' config

  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .

use_remote_storage: false
draft_mode: false
prev_task_id: null
