defaults:
  - _self_
  - datamodule: simple
  - net: mlp
  - optimizer: adam
  - model: cla
  - callbacks: default
  - trainer: default

  - experiment: null

  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .

data_type: "implicit"
clearml: false
use_remote_storage: false
draft_mode: false
prev_task_id: null
