defaults:
  - _self_
  - datamodule: simple
  - net: mf
  - optimizer: sgd
  - model: reg
  - callbacks: default
  - trainer: default

  - experiment: null

  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .

data_type: "explicit"
execute_locally: true
draft_mode: false
prev_task_id: null
