defaults:
  - datamodule: simple
  - model: mlp
  - callbacks: default
  - trainer: default
  
  - experiment: null  # Choose one from 'experiment' config

  - override hydra/job_logging: custom
  - _self_  # Primary config overrides values of configs from the Defaults List


hydra:
  output_subdir: null
  run:
    dir: .

project_name: "MyProject"
tags: ["${now:%Y-%m-%d}"]
data_processing_task_id: null
