defaults:
  - _self_
  - datamodule: simple.yaml
  - model: mf_sim_reg.yaml
  - callbacks: default.yaml

  - experiment: null

  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .

data_type: "explicit"
execute_locally: true
execute_remotely: false
prev_task_id: null
