defaults:
  - _self_
  - datamodule: default.yaml
  - model: mlp.yaml
  - callbacks: default.yaml
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .

execute_remotely: true
prev_task_id: null
