defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

# Preprocess
split_ratio: 0.7

# Train
n_steps: 200
lr: 0.01