hydra:
  run:
    dir: logs/preprocess/${now:%Y-%m-%d}_${now:%H-%M-%S}/

cwd: ${hydra:runtime.cwd}
raw_data_dir: ${cwd}/data/raw_data
processed_data_dir: ${cwd}/data/processed

raw_data_path: ${raw_data_dir}/data.csv
split_ratio: 0.7
train_data_path: ${processed_data_dir}/train.csv
test_data_path: ${processed_data_dir}/test.csv