early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/loss"
  mode: "min"
  patience: 2

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_last: true
  save_top_k: 0
  monitor: "val/loss"
  mode: "min"
