model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  filename: "best_model"
  save_last: false
  save_top_k: 1
  monitor: "val/ndcg"
  mode: "max"

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/ndcg"
  mode: "max"
  patience: 20

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
