model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_last: true
  save_top_k: 0
  monitor: "val/ndcg"
  mode: "max"

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/ndcg"
  mode: "max"
  patience: 20

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
