_target_: src.training.models.task.BPRClassificationTask

net:
  _target_: src.training.models.net.MF
  n_users: 6040
  n_items: 3706
  embed_size: 24

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-4
