_target_: src.training.models.task.BPRClassificationTask

net:
  _target_: src.training.models.net.MLP
  n_users: 6040  # 28597
  n_items: 3706  # 6733
  n_factors: 15
  n_layers: 3
  dropout: 0.5

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-4
