name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .
      - name: Run black
        run: black . --check --verbose
      - name: Run flake8
        run: flake8 .
      - name: Run isort
        run: isort . --check --verbose
      - name: Test with pytest
        run: pytest tests/
